# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jong Hak
description: '' # write a nice description for your blog
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://jong-hak-kim.github.io/' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
github:
  username: jong-hak-kim

social:
  name: Develop
  email: whdgkr9070@naver.com
  links:
  - https://github.com/jong-hak-ki

# Build settings
markdown: kramdown

toc: true

permalink: '/:title/'

plugins: [jekyll-paginate]

paginate: 10
